### ISSUE TITLE
Validate target/topic URIs through link header

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-pubsub#7] opened 2019-03-18 11:07 UTC
The question emerged in #1:

> how do we validate `target` URIs? Do we provide inboxes for arbitrary URIs? We could somehow couple this to vocabs published using https://github.com/hbz/skohub-ssg, but this is not feasible e.g. for lobid-gnd which will not be published using the static site generator / hosted on skohub.io.

Discussing this with @literarymachine, we decided to do it like this:

1. Skohub user will have to add a link header to their topic that
   1. links to the LDN inbox with `rel="http://www.w3.org/ns/ldp#inbox"`
   2. links to the WebSub hub with `rel="hub"` (note that it also should include a link with `rel="self"` to specify "[t]he canonical URL for the topic ... which subscribers are expected to use for subscriptions")
2. LDN-target URLs/WebSub-topic URLs will be validated by checking whether the target's/topic's link header actually points to the inbox/hub.  If this is not the case they will be rejected.

**Comment by acka47** [comment] 2019-03-18 11:21
Here are the relevant parts of the specs.

From [paragraph 4 "Dicsovery" of the WebSub spec](https://www.w3.org/TR/websub/#discovery):

> The protocol currently supports the following discovery mechanisms. Publishers MUST implement at least one of them:
>
> - Link Headers [RFC5988]: the publisher SHOULD include at least one Link Header [RFC5988] with rel=hub (a hub link header) as well as exactly one Link Header [RFC5988] with rel=self (the self link header)
> - If the topic is an XML based feed, publishers SHOULD use embedded link elements as described in Appendix B of Web Linking [RFC5988]. Similarly, for HTML pages, publishers SHOULD use embedded link elements as described in Appendix A of Web Linking [RFC5988].

From the [LDN spec's paragraph 3.1 "Discovery"](https://www.w3.org/TR/ldn/#discovery):

> Senders and consumers do the following to discover the Inbox URL:
>
> - make an HTTP HEAD or GET request on the target URL, and use the Link header with a rel value of http://www.w3.org/ns/ldp#inbox.
> - make an HTTP GET request on the target URL to retrieve an RDF representation [RDF 1.1], whose encoded RDF graph contains a relation of type http://www.w3.org/ns/ldp#inbox. The subject of that relation is target and the object is the Inbox.
>
> These may be carried out in either order, but if the first fails to result in an Inbox the second must be tried. **Senders and consumers should omit the Link header discovery when specifically targeting URIs with fragment identifiers.**

Emphasis by me. @literarymachine, please note that the Link header discovery makes problems with fragment identifiers which are used in many SKOS vocabularies. In the spec follows this note:

> If the target contains a fragment identifier, the fragment is not part of the request to the server. Senders and consumers should be aware that any Inbox found in the Link header will be for the resolved URL, without the fragment. See [Cool URIs for the Semantic Web - Hash URIs](https://www.w3.org/TR/cooluris).

**Comment by literarymachine** [comment] 2019-03-25 10:16
@acka47 see the updated README in b33d2be09c5592b774fb5f60ba0cb84c85d3dd5f

**Comment by acka47** [comment] 2019-03-25 10:53
I tried it out. Everything works fine until the last step:

```
$ curl -i "localhost:3000/inbox?target=https://lobid.org/gnd/118696432" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'
HTTP/1.1 400 Bad Request
X-Powered-By: Express
Date: Mon, 25 Mar 2019 10:51:25 GMT
Connection: keep-alive
Content-Length: 0

```

For comparison:
```
$ curl -i "localhost:3000/inbox?target=https://lobid.org/gnd/118696432"
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 128
ETag: W/"80-SOFRHzdp13Uu6B+zqLgdTlqWxjA"
Date: Mon, 25 Mar 2019 10:52:58 GMT
Connection: keep-alive

{"@context":"http://www.w3.org/ns/ldp","@id":"http://localhost:3000/inbox?target=https://lobid.org/gnd/118696432","contains":[]}
```

**Comment by literarymachine** [comment] 2019-03-25 13:40
> Everything works fine until the last step

This is expected behavior. https://lobid.org/gnd/118696432 does not provide the link headers, which are required as you describe in https://github.com/hbz/skohub-pubsub/issues/7#issue-422159712. See the README in https://github.com/hbz/skohub-pubsub/commit/b33d2be09c5592b774fb5f60ba0cb84c85d3dd5f for how to locally run a dummy publisher delivering the necessary link headers.

**Comment by dr0i** [comment] 2019-03-25 14:05
Although I don't comprehend how it works, I've updated the README a bit to make the proper port and address more clear. However as @acka47 I don't understand how to run the last step ("foo-bar") also I think I run a dummy publisher. I note, however, if use the _subscriber's_ port the subscriber logs the "foo-bar". I doubt that this is the way to use it, so I didn't took that into the README.

**Comment by literarymachine** [comment] 2019-03-25 16:03
@dr0i thx for https://github.com/hbz/skohub-pubsub/commit/ef50be608204711df16e6257de0bbdf635d18263, this documents the last step correctly!

**Comment by fsteeg** [comment] 2019-03-26 11:01
I have the same issue as @dr0i: `received {"foo": "bar"}` is only logged if I send to the *subscriber*:

`curl -v "localhost:45401/inbox?target=https://lobid.org/gnd/118696432" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'`

Where `45401` is the port I see when starting the subscriber:

`node src/subscriber.js http://127.0.0.1:3000/hub http://127.0.0.1:32925/https://lobid.org/gnd/118696432`
`Subscriber listening { address: '::', family: 'IPv6', port: 45401 }`
`received {"foo": "bar"}`

Then, however, everything is logged, even other topics. If I actually send it to the hub, nothing is logged:

`curl -v "localhost:3000/inbox?target=https://lobid.org/gnd/118696432" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'`
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /inbox?target=/https://lobid.org/gnd/118696432 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/ld+json
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
< HTTP/1.1 400 Bad Request
< X-Powered-By: Express
< Date: Tue, 26 Mar 2019 10:50:02 GMT
< Connection: keep-alive
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

One thing I noticed in the publisher, when starting the subscriber, it logged:

`node src/publisher.js`
`Publisher listening { address: '127.0.0.1', family: 'IPv4', port: 32925 }`
`/https://lobid.org/gnd/118696432` (with a leading slash)

I tried using that (`curl -v "localhost:3000/inbox?target=/https://lobid.org/gnd/118696432" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'`), but got the same result as above (although I get the response immediately, while the first one always takes a while between completed request and response).

**Comment by literarymachine** [comment] 2019-03-26 11:34
> I have the same issue as @dr0i: received {"foo": "bar"} is only logged if I send to the subscriber:

The subscriber is a dummy component. It is used to subscribe to a hub, but will log anything sent to it, be it from a hub or not. Strictly speaking, the subscriber is out of scope for this project, so I kept to a bare minimum.

> If I actually send it to the hub, nothing is logged:
    curl -v "localhost:3000/inbox?target=https://lobid.org/gnd/118696432" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'

This is expected behavior. This issue here is about validating the topic URIs in the Hub before accepting notifications (maybe @acka47 can elaborate in more detail in person). This is done by investigating the Link headers in the target - and until https://github.com/hbz/lobid-gnd/issues/184 is implemented, lobid.org does not set these. That is why you get a 400 Bad Request when trying to POST to an inbox of a lobid.org-target.

This is also why I added another dummy component, a publisher that will deliver those headers for any URL. See https://github.com/hbz/skohub-pubsub/commit/ef50be608204711df16e6257de0bbdf635d18263, perhaps with @dr0i.

**Comment by fsteeg** [comment] 2019-03-26 11:45
> This is also why I added another dummy component, a publisher that will deliver those headers for any URL. See ef50be6, perhaps with @dr0i.

But I'm running that publisher. @dr0i is investigating why it's working for him but not for me.

**Comment by dr0i** [comment] 2019-03-26 12:09
Um. It works when prefixing the "target" with the URL of the publisher, e.g. so:

> curl -vvvi "localhost:3000/inbox?target=http://127.0.0.1:45254/https://lobid.org/gnd/118696432"   -H "Content-Type: application/ld+json"  -d '{"foo": "bar"}'

But this usage is not intended, right, because that's what the pubsub shall do - gathering all the publishers "topics" and provide these if someone asks about this topic.
So I did make it work just by accident.

**Comment by literarymachine** [comment] 2019-03-26 12:31
> It works when prefixing the "target" with the URL of the publisher,

Ah, I see the misunderstanding now. The terminology is a bit confusing here, since we are following two specs. Anyways, the publisher *is* the target:

```
 curl "localhost:3000/inbox?target=http://127.0.0.1:40499/some/random/topic" -H "Content-Type: application/ld+json" -d '{"foo": "bar"}'
```

**Comment by fsteeg** [comment] 2019-03-26 12:56
With @literarymachine's help and his tweaked README instructions it's now working here. +1.

**Comment by acka47** [comment] 2019-03-26 12:57
Great, we all got it to work by now. I moved https://github.com/hbz/lobid-gnd/issues/184 to ready. Hopefully, @fsteeg can implement it by the end of the week so that we have a more realistic test case.

**Comment by fsteeg** [comment] 2019-03-26 13:11
But https://github.com/hbz/lobid-gnd/issues/184 is also a weird, non-realistic setup, with its localhost URIs, isn't it? Would it not make sense to stick to a local publisher for local testing? And add the links to `test.lobid.org` when we have something like `test.skohub.io` running?

**Comment by acka47** [comment] 2019-03-26 13:20
> But https://github.com/hbz/lobid-gnd/issues/184 is also a weird, non-realistic setup, with its localhost URIs, isn't it?

Yes, that is why we would do it on staging. I see no problem with that.

> Would it not make sense to stick to a local publisher for local testing? And add the links to test.lobid.org when we have something like test.skohub.io running?

As we all have tested this locally, I guess it is not so important to implement https://github.com/hbz/lobid-gnd/issues/184. I am ok with waiting. What do you think, @literarymachine ?

**Closed as completed** 2019-03-26 13:23 UTC

**Comment by literarymachine** [comment] 2019-03-26 13:25
> I am ok with waiting. What do you think, @literarymachine ?

Well, it depends on what we are waiting for. We only have https://github.com/hbz/skohub-pubsub/issues/5 in the backlog. This is only relevant for https://github.com/hbz/skohub-deck/issues/1. How would you like to continue? Should I deploy the pubsub server to a test system? Are you going to implement a subscriber for lobid-gnd notifications?
